# Generated by Django 2.0 on 2020-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='lastname',
            new_name='password',
        ),
    ]
