# Generated by Django 2.0 on 2020-05-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marks_student_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks',
            new_name='mark',
        ),
    ]
