# Generated by Django 2.0 on 2020-05-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200520_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='link_teacher',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lib_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.mark'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lib_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
