# Generated by Django 2.0 on 2020-05-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200530_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='link_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
