# Generated by Django 2.0 on 2020-05-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200530_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='link_teacher',
        ),
    ]
