# Generated by Django 2.0 on 2020-05-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_login_link_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lib_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lib_id',
        ),
    ]
