# Generated by Django 2.0 on 2020-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200530_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lib',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lib',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
