# Generated by Django 2.0 on 2020-06-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200606_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='college_id',
        ),
    ]
