# Generated by Django 2.0 on 2020-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200607_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(max_length=50, null=True)),
                ('query', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
