# Generated by Django 2.0 on 2020-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200608_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
