# Generated by Django 2.0 on 2020-06-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_query_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='query',
            new_name='querytb',
        ),
    ]
